swagger: "2.0"
info:
  description: "API de proyecto GATES"
  version: "1.0"
  title: "Gates Segutal"
servers:
  - url: http://prepro-back-aws.segutalmexico.com/api,
  description: 'Development'
  - url: http://my-production-aws.segutalmexico.com/api
  description: 'Production'
basePath: "/api"
tags:
- name: "Viajes"
  description: ""
- name: "Liquidaciones"
  description: ""
- name: "Reportes"
  description: ""
- name: "Finanzas"
  description: ""
- name: "Registros"
  description: "Servicios, Empleados, Unidad Motriz, Arrastre, Mercancía, Proveedores, Base, Cliente, Utilitarias."
- name: "Covid"
  description: "Usuario y Admin."
- name: "Equipos"
  description: ""
- name: "Capacitación"
  description: "Usuario y Admin."
- name: "Dashboard"
  description: "Panel de administración."
schemes:
- "http"
paths:
  /pet:
    post:
      tags:
      - "pet"
      summary: "Add a new pet to the store"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Pet"
      responses:
        "405":
          description: "Invalid input"
    

definitions:
  
  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Category"
  Pet:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
        format: "int64"
      category:
        $ref: "#/definitions/Category"
      name:
        type: "string"
        example: "doggie"
      photoUrls:
        type: "array"
        xml:
          name: "photoUrl"
          wrapped: true
        items:
          type: "string"
    xml:
      name: "Pet"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"